### ISSUE TITLE
reward-based e-prop

### ISSUE THREAD

**Issue by ShuJz** [IGITUGraz/eligibility_propagation#2]
https://github.com/IGITUGraz/eligibility_propagation/blob/7dd1558b5e2ff85b3b2b58e933cb2103a12f2a3b/Figure_4_and_5_ATARI/main.py#L235-L239

It seems the BPTT still be used here. How is e-prop used in this task? There is not an implementation of e-prop like you did here
 
https://github.com/IGITUGraz/eligibility_propagation/blob/7dd1558b5e2ff85b3b2b58e933cb2103a12f2a3b/Figure_3_and_S7_e_prop_tutorials/models.py#L382-L398.

**Comment by franzscherr** [comment]
Hi @ShuJz!
Thanks for your interest.

We perform a trick with autodifferentiation, which is equivalent as hardcoding e-prop.
Numerically, the trick is verified in [numerical_verification.py](https://github.com/IGITUGraz/eligibility_propagation/blob/master/numerical_verification_eprop_hardcoded_vs_autodiff.py) and expresses itself in the example that you pointed out in https://github.com/IGITUGraz/eligibility_propagation/blob/7dd1558b5e2ff85b3b2b58e933cb2103a12f2a3b/Figure_4_and_5_ATARI/alif_eligibility_propagation.py#L125-L126
for the recurrent network, and for example in
https://github.com/IGITUGraz/eligibility_propagation/blob/7dd1558b5e2ff85b3b2b58e933cb2103a12f2a3b/Figure_4_and_5_ATARI/spiking_agent.py#L124
for the spiking CNN

**Comment by ShuJz** [comment]
Thanks for your reply.
I reviewed the code you mentioned, but still have a question with this code:
https://github.com/IGITUGraz/eligibility_propagation/blob/7dd1558b5e2ff85b3b2b58e933cb2103a12f2a3b/numerical_verification_eprop_factorization_vs_BPTT.py#L83

when you calculate the gradient by using hard-code eprop, you used the `tf.gradients()` to get `dE_dz`, but the `tf.gradients()` is based on BP and you set `stop_z_gradients=False`, that means when you calculate the derivative of `spikes` the error still propagate through time as BPTT do.

I have also written a script to investigate that:
https://github.com/ShuJz/eligibility_propagation/blob/master/test_eprop.py

here is the output of the script:

> S1: EligALIF model BPTT vs. eprop-autodiff
  Maximum element wise errors(inputs): 0.0
  Maximum element wise errors(target): 0.0
  Maximum element wise errors(w_in): 0.0
  Maximum element wise errors(w_rec): 0.0
  Maximum element wise errors(w_out): 0.0
  Maximum element wise errors(spikes): 0.0
  Maximum element wise errors(out): 0.0
  Maximum element wise errors(eligibility_traces): 0.0
  Maximum element wise errors(learning_signals): 0.11414007097482681
  Maximum element wise errors(gradients_hardcode): 1.9996122121810913
  Maximum element wise errors(gradients_autodiff): 1.99961256980896
  ######################################
  S2: EligALIF model autodiff vs. hardcode
  BPTT vs. eprop-hardcode
  Maximum element wise errors(gradients BPTT vs. eprop-hardcode): 6.219636893185776e-14
  eprop-autodiff vs. eprop-hardcode
  Maximum element wise errors(gradients eprop-autodiff vs. eprop-hardcode): 1.3024242871261665e-13
  ######################################
  S3: CustomALIF model BPTT vs. eprop-autodiff
  Maximum element wise errors(inputs): 0.0
  Maximum element wise errors(target): 0.0
  Maximum element wise errors(w_in): 0.0
  Maximum element wise errors(w_rec): 0.0
  Maximum element wise errors(w_out): 0.0
  Maximum element wise errors(spikes): 0.0
  Maximum element wise errors(out): 0.0
  There is no eligibility_traces.
  There is no learning_signals.
  There is no gradients_hardcode.
  Maximum element wise errors(gradients_autodiff): 1.9996129274368286
  ######################################

From this output:
- from S1: EligALIF model BPTT vs. eprop-autodiff
  - `eligibility_traces` is equal while `learning_signals` is different, that means the `stop_z_gradients` will affect the calculation of `learning_signals` when `tf.gradients()` is used.
  - 'gradients_autodiff' and `gradients_autodiff` are different between BPTT and eprop-autodiff model, that is caused by the different route of error propagate.
- from S3: CustomALIF model BPTT vs. eprop-autodiff
  - `gradients_autodiff` are still different between BPTT and eprop-autodiff model, the BPTT and eprop-autodiff seems like not equivalently.

Since eprop still use BPTT (when calculate `dE_dz`), does eprop have lower complexity when compared to BPTT?

It seems the model CustomALIF has essentially difference when `stop_z_gradients` is set to `False` or `True`, will these two models (`CustomALIF(stop_z_gradients=False)`, `CustomALIF(stop_z_gradients=True)`) really have similar performance?

**Comment by guillaumeBellec** [comment]
Yes, the script [numerical_verification_eprop_factorization_vs_BPTT.py](https://github.com/IGITUGraz/eligibility_propagation/blob/7dd1558b5e2ff85b3b2b58e933cb2103a12f2a3b/numerical_verification_eprop_factorization_vs_BPTT.py) computes the exact same loss gradient as in BPTT.

This script is meant to be a numerical proof of equation (1) from the paper and not how we implement e-prop. This equation is a mathematical property of e-traces [dz/dW]_local, it tells us that we get the exact same gradient as BPTT if we merge e-traces with exact learning signals dE/dz computed with tf.gradients(...). Indeed, this total derivative dE/dz requires to back propagate through time. This is why we approximate the learning signals with the partial derivatives in equation (4), this defines the e-prop algorithm.

The e-prop algorithm is implemented in the other script [numerical_verification_eprop_hardcoded_vs_autodiff.py](https://github.com/IGITUGraz/eligibility_propagation/blob/7dd1558b5e2ff85b3b2b58e933cb2103a12f2a3b/numerical_verification_eprop_hardcoded_vs_autodiff.py#L89).
There we replace the learning signals dE/dz with equation (4) explicitly. There is no tf.gradients(...) anymore. This second script shows that it is numerically equivalent to compute e-prop gradients in this way or to apply BPTT with the option `stop_z_gradients=true`.

**Comment by ShuJz** [comment]
Thank you very much for your patient answers.
